# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### RESOURCES: System Configuration
  ########################################
  resources:
   ### Clone dotfiles repository
   ### -------------------------------------
   - resource: GitDsc/GitClone
     id: mydotifiles
     dependsOn:
       - git
     directives:
       description: Clone WinGet CLI GitHub repository
       allowPrerelease: true
     settings:
       HttpsUrl: https://github.com/acangialosi/dotfiles
       RootDirectory: c:\src
       Ensure: Present
   ### Configure Visual Studio settings
   ### -------------------------------------
   - resource: Environment
     directives:
      description: Set Visual Studio Unified Settings Profile environment variable
     settings:
      Name: VS_UNIFIED_SETTINGS_PROFILE
      Value: 'c:\src\dotfiles\visualstudio\settings\devbox'
      Ensure: Present