$schema: "1.0"
name: "devbox-customization"
tasks:
  - name: git-clone
    description: Clone this repository into C:\Workspaces
    parameters:
      repositoryUrl: https://github.com/acangialosi/dotfiles.git
      directory: c:\workspaces
  - name: winget
    parameters:
      configurationFile: 'c:\workspaces\dotfiles\.configurations\ready-for-me.dsc.yaml'
      runAsUser: true
